### ISSUE TITLE
loom

### ISSUE THREAD

**Issue by tmanolat** [chris4mich/mini-project#1]
@chris4mich μπορεις να βάλεις τα loom videos με δυο λογάκια ως markdown σε ένα README.md στο root folder

αλλιως με email

**Comment by chris4mich** [comment]
Χαίρετε,  Σας έχω αποστείλει το link από το loom στα emails. Φτιάχνω το README.md και  σας ενημερώνω. Με εκτίμηση,Χρήστος Μιχαλόπουλος From: TILEMAHOS MANOLATOSSent: Τρίτη, 17 Ιανουαρίου 2023 12:44 μμTo: chris4mich/mini-projectCc: Christos Michalopoulos; MentionSubject: [chris4mich/mini-project] loom (Issue ***@***.*** μπορεις να βάλεις τα loom videos με δυο λογάκια ως markdown σε ένα README.md στο root folderαλλιως με email—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
